set echo off
set feedback off
set linesize 512

prompt
prompt All Table Partitions in Database
prompt

break on TABLE_OWNER on TABLE_NAME skip 1


SELECT TABLE_OWNER, 
    TABLE_NAME, TABLESPACE_NAME,
		 PARTITION_NAME, PARTITION_POSITION,
		 LOGGING, HIGH_VALUE, PCT_FREE,
		 PCT_USED, INI_TRANS, MAX_TRANS,
		 INITIAL_EXTENT, NEXT_EXTENT,
		 MAX_EXTENT, PCT_INCREASE
	FROM SYS.DBA_TAB_PARTITIONS   where 
  ORDER BY  TABLE_OWNER, TABLE_NAME, PARTITION_POSITION;


SELECT	 -- TABLE_OWNER, 
    TABLE_NAME, TABLESPACE_NAME,
		 PARTITION_NAME, PARTITION_POSITION,
		 LOGGING, HIGH_VALUE, PCT_FREE,
		 PCT_USED, INI_TRANS, MAX_TRANS,
		 INITIAL_EXTENT, NEXT_EXTENT,
		 MAX_EXTENT, PCT_INCREASE
	
  
  select distinct table_name FROM 
  --   SYS.DBA_TAB_PARTITIONS
  USER_TAB_PARTITIONS A where -- table_name ='CR_TRANSACTION_HIST'  and 
  not exists (select 'x' from USER_TAB_PARTITIONS B where a.TABLE_NAME =b.TABLE_NAME and b.PARTITION_NAME like '%MAX' )
ORDER BY -- TABLE_OWNER, 
TABLE_NAME, PARTITION_POSITION;



SELECT	 -- TABLE_OWNER, 
    TABLE_NAME, TABLESPACE_NAME,
		 PARTITION_NAME, PARTITION_POSITION,
		 LOGGING, HIGH_VALUE, PCT_FREE,
		 PCT_USED, INI_TRANS, MAX_TRANS,
		 INITIAL_EXTENT, NEXT_EXTENT,
		 MAX_EXTENT, PCT_INCREASE
	FROM 
  --   SYS.DBA_TAB_PARTITIONS
  USER_TAB_PARTITIONS A where  table_name ='CHARGEBACK' 
  -- not exists (select 'x' from USER_TAB_PARTITIONS B where a.TABLE_NAME =b.TABLE_NAME and b.PARTITION_NAME like '%MAX' )
